### ISSUE TITLE
V = np.zeros([int(TotalPatNum)]+ksizes); # create D+1 dimension volume

### ISSUE THREAD

**Issue by arunpramod** [zhiyuan0112/Bi-3DQRNN#1]
Traceback (most recent call last):

  File "/media/ipcvworkstation2/New Volume/Bi-3DQRNN-main/utility/lmdb_data.py", line 225, in <module>
    create_icvl64_31()

  File "/media/ipcvworkstation2/New Volume/Bi-3DQRNN-main/utility/lmdb_data.py", line 138, in create_icvl64_31
    load=h5py.File, augment=True,

  File "/media/ipcvworkstation2/New Volume/Bi-3DQRNN-main/utility/lmdb_data.py", line 43, in create_lmdb_train
    data = preprocess(data)

  File "/media/ipcvworkstation2/New Volume/Bi-3DQRNN-main/utility/lmdb_data.py", line 27, in preprocess
    temp = Data2Volume(temp, ksizes=ksizes, strides=list(strides[i]))

  File "/media/ipcvworkstation2/New Volume/Bi-3DQRNN-main/utility/util.py", line 41, in Data2Volume
    V = np.zeros([int(TotalPatNum)]+ksizes); # create D+1 dimension volume

ValueError: negative dimensions are not allowed
![error](https://user-images.githubusercontent.com/95032985/150761669-14b428a4-34f7-4664-b6d8-e652a54247b4.jpg)

**Comment by zhiyuan0112** [comment]
Really really sorry for replying so late.
The expected shape of **temp** is (c,h,w), where **c** is number of channels (equals to 31 in ICVL dataset). But the original shape of ICVL is (h,w,c).
So, in the `preprocess()` function (embedded in `create_lmdb_train`), we need to reshape `data` from (h,w,c) to (c,h,w). 

```python3
data = minmax_normalize(data if data.shape[1]==data.shape[2] else data.transpose((2,0,1)))
```

I've fixed the bug : )
